# Generated by Django 4.0.5 on 2022-11-04 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MaesCarentes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='mae',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MaesCarentes.mae'),
        ),
    ]
